#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v18
# autospec commit: f35655a
#
# Source0 file verified with key 0x350D0B0705E9C3CB (nneul@neulinger.org)
#
Name     : cracklib
Version  : 2.10.2
Release  : 54
URL      : https://github.com/cracklib/cracklib/releases/download/v2.10.2/cracklib-2.10.2.tar.gz
Source0  : https://github.com/cracklib/cracklib/releases/download/v2.10.2/cracklib-2.10.2.tar.gz
Source1  : https://github.com/cracklib/cracklib/releases/download/v2.10.2/cracklib-2.10.2.tar.gz.asc
Source2  : 350D0B0705E9C3CB.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0+ LGPL-2.1
Requires: cracklib-bin = %{version}-%{release}
Requires: cracklib-data = %{version}-%{release}
Requires: cracklib-lib = %{version}-%{release}
Requires: cracklib-license = %{version}-%{release}
Requires: cracklib-locales = %{version}-%{release}
Requires: cracklib-man = %{version}-%{release}
Requires: cracklib-python = %{version}-%{release}
Requires: cracklib-python3 = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : gnupg
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This package is an updated/modernized distribution of CrackLib as
previously release by Alec Muffett. Pretty much all of the files have
been modified in some way to allow for this modernization and to
apply numerous bug fixes and patches.

%package bin
Summary: bin components for the cracklib package.
Group: Binaries
Requires: cracklib-data = %{version}-%{release}
Requires: cracklib-license = %{version}-%{release}

%description bin
bin components for the cracklib package.


%package data
Summary: data components for the cracklib package.
Group: Data

%description data
data components for the cracklib package.


%package dev
Summary: dev components for the cracklib package.
Group: Development
Requires: cracklib-lib = %{version}-%{release}
Requires: cracklib-bin = %{version}-%{release}
Requires: cracklib-data = %{version}-%{release}
Provides: cracklib-devel = %{version}-%{release}
Requires: cracklib = %{version}-%{release}

%description dev
dev components for the cracklib package.


%package lib
Summary: lib components for the cracklib package.
Group: Libraries
Requires: cracklib-data = %{version}-%{release}
Requires: cracklib-license = %{version}-%{release}

%description lib
lib components for the cracklib package.


%package license
Summary: license components for the cracklib package.
Group: Default

%description license
license components for the cracklib package.


%package locales
Summary: locales components for the cracklib package.
Group: Default

%description locales
locales components for the cracklib package.


%package man
Summary: man components for the cracklib package.
Group: Default

%description man
man components for the cracklib package.


%package python
Summary: python components for the cracklib package.
Group: Default
Requires: cracklib-python3 = %{version}-%{release}

%description python
python components for the cracklib package.


%package python3
Summary: python3 components for the cracklib package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cracklib package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 350D0B0705E9C3CB' gpg.status
%setup -q -n cracklib-2.10.2
cd %{_builddir}/cracklib-2.10.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722872005
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-default-dict-path=/usr/share/cracklib/pw_dict
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722872005
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cracklib
cp %{_builddir}/cracklib-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/cracklib/3ac522f07da0f346b37b29cd73a60f79e992ffba || :
cp %{_builddir}/cracklib-%{version}/README-LICENSE %{buildroot}/usr/share/package-licenses/cracklib/30d6e5f96b35b286ffd2336213552240b2835b46 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang cracklib
## install_append content
chmod 755 util/cracklib-format util/cracklib-packer
util/cracklib-format dicts/cracklib-small | util/cracklib-packer %{buildroot}/usr/share/cracklib/pw_dict
#gzip -9 %{buildroot}/usr/share/cracklib/pw_dict.pwd
rm %{buildroot}/usr/share/cracklib/cracklib-small
rm %{buildroot}/usr/share/cracklib/cracklib.magic
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cracklib-check
/usr/bin/cracklib-format
/usr/bin/cracklib-packer
/usr/bin/cracklib-unpacker
/usr/bin/cracklib-update
/usr/bin/create-cracklib-dict

%files data
%defattr(-,root,root,-)
/usr/share/cracklib/pw_dict.hwm
/usr/share/cracklib/pw_dict.pwd
/usr/share/cracklib/pw_dict.pwi

%files dev
%defattr(-,root,root,-)
/usr/include/crack.h
/usr/include/packer.h
/usr/lib64/libcrack.so
/usr/share/man/man3/FascistCheck.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcrack.so.2
/usr/lib64/libcrack.so.2.9.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cracklib/30d6e5f96b35b286ffd2336213552240b2835b46
/usr/share/package-licenses/cracklib/3ac522f07da0f346b37b29cd73a60f79e992ffba

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/cracklib-check.8
/usr/share/man/man8/cracklib-format.8
/usr/share/man/man8/cracklib-update.8
/usr/share/man/man8/create-cracklib-dict.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f cracklib.lang
%defattr(-,root,root,-)

