#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cracklib
Version  : 2.9.5
Release  : 19
URL      : http://downloads.sourceforge.net/cracklib/cracklib-2.9.5.tar.gz
Source0  : http://downloads.sourceforge.net/cracklib/cracklib-2.9.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0+ LGPL-2.1
Requires: cracklib-bin
Requires: cracklib-lib
Requires: cracklib-data
Requires: cracklib-locales
Requires: cracklib-python
BuildRequires : pkgconfig(zlib)
BuildRequires : python-dev

%description
This package is an updated/modernized distribution of CrackLib as
previously release by Alec Muffett. Pretty much all of the files have
been modified in some way to allow for this modernization and to
apply numerous bug fixes and patches.

%package bin
Summary: bin components for the cracklib package.
Group: Binaries
Requires: cracklib-data

%description bin
bin components for the cracklib package.


%package data
Summary: data components for the cracklib package.
Group: Data

%description data
data components for the cracklib package.


%package dev
Summary: dev components for the cracklib package.
Group: Development
Requires: cracklib-lib
Requires: cracklib-bin
Requires: cracklib-data
Provides: cracklib-devel

%description dev
dev components for the cracklib package.


%package lib
Summary: lib components for the cracklib package.
Group: Libraries
Requires: cracklib-data

%description lib
lib components for the cracklib package.


%package locales
Summary: locales components for the cracklib package.
Group: Default

%description locales
locales components for the cracklib package.


%package python
Summary: python components for the cracklib package.
Group: Default

%description python
python components for the cracklib package.


%prep
%setup -q -n cracklib-2.9.5

%build
%configure --disable-static --with-default-dict-path=/usr/share/cracklib/pw_dict
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang cracklib
## make_install_append content
chmod 755 util/cracklib-format util/cracklib-packer
util/cracklib-format dicts/cracklib-small | util/cracklib-packer %{buildroot}%{_datadir}/cracklib/pw_dict
gzip -9 %{buildroot}%{_datadir}/cracklib/pw_dict.pwd
rm %{buildroot}%{_datadir}/cracklib/cracklib-small
rm %{buildroot}%{_datadir}/cracklib/cracklib.magic
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cracklib-check
/usr/bin/cracklib-format
/usr/bin/cracklib-packer
/usr/bin/cracklib-unpacker
/usr/bin/create-cracklib-dict

%files data
%defattr(-,root,root,-)
/usr/share/cracklib/pw_dict.hwm
/usr/share/cracklib/pw_dict.pwd.gz
/usr/share/cracklib/pw_dict.pwi

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*

%files locales -f cracklib.lang 
%defattr(-,root,root,-)

